#!/usr/bin/env python3
"""Tests the PURE egress model/renderer (tools/drvps_egress_model.py). No IO. PLAN Task 0.1.
Includes the byte-exact POST-M render golden vs the live managed squid.conf body (Stage M folded)."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
import drvps_egress_model as M  # noqa

npass = [0]; nfail = [0]
def ok(c, m):
    if c: npass[0] += 1
    else: nfail[0] += 1; print("FAIL:", m)

# ---- canon_fqdn accept/reject table (exact ReasonCode) ----
def cf(v): return M.canon_fqdn(v)
ok(cf("callback.crm.example") == ("callback.crm.example", None), "fqdn ok")
ok(cf("Callback.CRM.Example") == ("callback.crm.example", None), "fqdn lowercased")
ok(cf("x--y.example") == ("x--y.example", None), "double-hyphen interior ok")
ok(cf("xn--80ak6aa92e.example")[0] == "xn--80ak6aa92e.example", "IDN xn-- ok")
for bad, reason in [
    ("-i", "leading-dash"), ("*.x.com", "wildcard"), (".x.com", "bad-label"),
    ("x.com.", "bad-label"), ("a..b.com", "bad-label"), ("1.2.3.4", "ip-literal"),
    ("http://x.com", "url"), ("x.com/p", "url"), ("x.com:443", "port"),
    ("::1", "port"), ("localhost", "single-label"), ("café.com", "non-ascii"),
    ("a" * 64 + ".com", "too-long"), (("a." * 130) + "com", "too-long"),
    (123, "bad-type"), ("", "single-label"),
]:
    r = cf(bad)
    ok(r == (None, reason), "reject %r -> %s (got %r)" % (bad, reason, r))

# ---- load_model: legacy mirrors + splice validation ----
LIVE_MIRRORS = ("mirrors.fedoraproject.org download.fedoraproject.org dl.fedoraproject.org "
                "deb.debian.org cloud.debian.org security.debian.org archive.ubuntu.com "
                "security.ubuntu.com dl.rockylinux.org repo.almalinux.org "
                "mirror.stream.centos.org download.opensuse.org dl-cdn.alpinelinux.org").split()
m0 = M.load_model({"mirror_allowlist": list(LIVE_MIRRORS)})
ok(m0.mirrors == tuple(LIVE_MIRRORS), "legacy mirrors load in order")
ok(m0.splices == (), "no splices by default")
ms = M.load_model({"mirror_allowlist": ["deb.debian.org"],
                   "splice_allowlist": [{"host": "callback.crm.example", "port": 443}]})
ok(ms.splices == (("callback.crm.example", 443),), "splice loads")

def rej_model(fleet, reason, label):
    try:
        M.load_model(fleet); ok(False, "%s should raise" % label)
    except M.EgressError as e:
        ok(e.reason == reason, "%s -> %s (got %s)" % (label, reason, e.reason))

rej_model({"mirror_allowlist": ["deb.debian.org"], "splice_allowlist": [{"host": "deb.debian.org"}]},
          "overlap", "mirror/splice overlap")
rej_model({"splice_allowlist": [{"host": "x.com"}, {"host": "X.com"}]}, "dup", "dup splice")
rej_model({"splice_allowlist": [{"host": "x.com", "port": 0}]}, "bad-port", "bad port")
rej_model({"splice_allowlist": [{"host": "x.com", "port": True}]}, "bad-port", "bool port")
rej_model({"splice_allowlist": [{"host": "x.com", "port": 8443}]}, "bad-port", "non-443 rejected (v1 443-only)")
rej_model({"splice_allowlist": [{"host": "x.com", "extra": 1}]}, "unknown-field", "unknown field")
rej_model({"mirror_allowlist": ["bad_host.com"]}, "bad-label", "illegal mirror char (Stage V canon)")
rej_model({"mirror_allowlist": ["nodot"]}, "single-label", "single-label mirror (Stage V canon)")
rej_model({"mirror_allowlist": ["deb.debian.org", "Deb.Debian.Org"]}, "dup", "duplicate mirror (canon-folded) fails closed")
rej_model({"splice_allowlist": [{"host": "-i.com"}]}, "leading-dash", "splice leading-dash")

# ---- CA parents / nameConstraints / hash (matches _drvps_ca_parents/_drvps_ca_nc) ----
parents = M.ca_parents(m0)
ok(parents == ["almalinux.org", "alpinelinux.org", "centos.org", "debian.org",
               "fedoraproject.org", "opensuse.org", "rockylinux.org", "ubuntu.com"],
   "derived CA parents sorted (got %r)" % parents)
nc = M.render_ca_name_constraints(m0)
ok(nc.startswith("excluded;IP:0.0.0.0/0.0.0.0,excluded;IP:0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0,permitted;DNS:almalinux.org"),
   "nc prefix + first permitted")
ok(M.ca_hash_input(m0) == nc, "ca_hash_input == nc")
try:
    M.ca_parents(M.load_model({"mirror_allowlist": ["mirror.example.net"]})); ok(False, "unknown family should fail")
except M.EgressError as e:
    ok(e.reason == "bad-label", "unknown CA family fails closed")
# a splice add must NOT change the CA hash
ok(M.ca_hash_input(M.load_model({"mirror_allowlist": list(LIVE_MIRRORS),
    "splice_allowlist": [{"host": "callback.crm.example"}]})) == nc, "splice add leaves CA hash unchanged")

# ---- BYTE-EXACT render golden -- the POST-M mirror-only managed body (Stage M -n/--client-requested
# folded; the pre-M Stage-0 no-op was proven + backed up separately, see egress-render-noop.sh) ----
LIVE_BODY = (
"# distro-rig-vps-managed squid.conf -- regenerated by dr-vps-setup; edit /etc/distro-rig-vps/fleet.json + --reapply-egress, NOT this file\n"
"http_port 10.123.0.1:3128 ssl-bump cert=/etc/squid/drvps-ca.pem generate-host-certificates=on dynamic_cert_mem_cache_size=4MB\n"
"sslcrtd_program /usr/lib64/squid/security_file_certgen -s /var/lib/ssl_db -M 4MB\n"
"acl drvps_guests src 10.123.0.0/24\n"
"acl mirror_sni ssl::server_name --client-requested " + " ".join(LIVE_MIRRORS) + "\n"
"acl mirror_dst dstdomain -n " + " ".join(LIVE_MIRRORS) + "\n"
"acl mirror_methods method GET HEAD\n"
"acl drvps_connect method CONNECT\n"
"acl drvps_https port 443\n"
"acl drvps_http port 80 443\n"
"acl step1 at_step SslBump1\n"
+ ("acl drvps_internal_dst dst " + " ".join(M.internal_deny_cidrs(m0, M.HostFacts())) + "\n") +
"ssl_bump peek step1\n"
"ssl_bump bump mirror_sni\n"
"ssl_bump terminate all\n"
"http_access deny !drvps_guests\n"
"http_access deny drvps_internal_dst\n"
"http_access allow drvps_connect mirror_dst drvps_https\n"
"http_access allow mirror_methods mirror_dst drvps_http\n"
"http_access deny all\n"
"coredump_dir /var/spool/squid\n"
"cache_dir ufs /var/spool/squid 8192 16 256\n"
"maximum_object_size 2048 MB\n"
"cache_mem 256 MB\n"
r"refresh_pattern -i \.(rpm|drpm|xml|gz|xz|bz2|sqlite)$ 10080 90% 43200" + "\n"
)
P = M.RenderParams(proxy_ip="10.123.0.1", proxy_src="10.123.0.0/24", cache_mb=8192,
                   maxobj_mb=2048, certgen_path="/usr/lib64/squid/security_file_certgen")
HF = M.HostFacts()
got = M.render_squid(m0, P, HF)
ok(got == LIVE_BODY, "render_squid BYTE-IDENTICAL to live body")
if got != LIVE_BODY:
    import difflib
    print("".join(difflib.unified_diff(LIVE_BODY.splitlines(True), got.splitlines(True),
                                        "live", "rendered")))
# empty splice_allowlist renders the mirror-only (post-M) baseline, no splice/revision lines
ok(M.render_squid(M.load_model({"mirror_allowlist": list(LIVE_MIRRORS), "splice_allowlist": []}), P, HF) == LIVE_BODY,
   "empty splice_allowlist == mirror-only baseline")
ok("# egress-model-revision" not in LIVE_BODY, "mirror-only has no revision line")
# F3 REGRESSION (external review): the internal-destination deny is rendered even in the mirror-only (NO-splice)
# DEFAULT config -- an allowlisted mirror that resolves via poisoned DNS/compromise to an internal IP is the same
# SSRF as a rebinding splice, so the `dst` deny must guard the always-on mirror path, ordered BEFORE its allow.
ok("acl drvps_internal_dst dst " in LIVE_BODY and "\nhttp_access deny drvps_internal_dst\n" in LIVE_BODY,
   "mirror-only config STILL renders the internal-destination deny (SSRF guard not splice-gated)")
ok(LIVE_BODY.index("http_access deny drvps_internal_dst") < LIVE_BODY.index("http_access allow drvps_connect mirror_dst"),
   "mirror-only: internal-deny ordered BEFORE the mirror allow")

# ---- SPLICE branch render (C-§4): conjunctive dst+sni, internal-deny, on_unsupported, revision ----
HF2 = M.HostFacts(drvps_subnets=("10.123.0.0/24",), host_ips=("192.0.2.10",))
msp = M.load_model({"mirror_allowlist": ["deb.debian.org"],
                    "splice_allowlist": [{"host": "callback.crm.example"}]})
body = M.render_squid(msp, P, HF2)
def has(line): return ("\n" + line + "\n") in ("\n" + body)
ok(has("acl splice_sni ssl::server_name --client-requested callback.crm.example"), "splice_sni --client-requested")
ok(has("acl splice_dst dstdomain -n callback.crm.example"), "splice_dst -n")
ok(has("ssl_bump splice step2 splice_dst splice_sni"), "conjunctive splice rule")
ok(has("ssl_bump bump step2 mirror_dst mirror_sni"), "conjunctive mirror bump rule")
ok(has("on_unsupported_protocol respond all"), "non-TLS pinned")
ok("acl drvps_internal_dst dst 0.0.0.0/8 127.0.0.0/8 10.0.0.0/8" in body and "10.123.0.0/24" in body and "192.0.2.10" in body,
   "internal-deny reserved + host_facts")
# the UNSPECIFIED addresses must be denied (connecting to 0.0.0.0 / :: reaches host loopback on Linux -- SSRF)
ok(all(c in body for c in ("0.0.0.0/8","::/128","198.18.0.0/15","240.0.0.0/4","64:ff9b:1::/48","fec0::/10")), "internal-deny covers unspecified/benchmark/reserved/local-NAT64/site-local")
# REGRESSION GUARD: prefixes that ENCODE an IPv4 address must NEVER be in the deny set -- squid stores every IPv4
# dst as IPv4-mapped, so `dst ::ffff:0:0/96` denies ALL IPv4 (total outage the container gate caught); and the
# well-known NAT64 prefix 64:ff9b::/96 is IANA globally-reachable and maps public IPv4 callbacks. The plain v4
# ranges already cover mapped-loopback because squid normalizes v4-mapped back to v4. See RESERVED_DENY_CIDRS.
ok(all(c not in body and c not in M.RESERVED_DENY_CIDRS for c in ("::ffff:0:0/96", "64:ff9b::/96")),
   "IPv4-encoding prefixes ::ffff:0:0/96 + 64:ff9b::/96 EXCLUDED (would deny public IPv4)")
# ORDERING: splice allow before mirror allow, both after internal-deny; ssl_bump peek<splice<bump<terminate
idx = {k: body.index(k) for k in [
    "ssl_bump peek step1", "ssl_bump splice step2", "ssl_bump bump step2", "ssl_bump terminate all",
    "http_access deny drvps_internal_dst", "http_access allow drvps_connect splice_dst",
    "http_access allow drvps_connect mirror_dst", "http_access deny all"]}
ok(idx["ssl_bump peek step1"] < idx["ssl_bump splice step2"] < idx["ssl_bump bump step2"] < idx["ssl_bump terminate all"],
   "ssl_bump ordering peek<splice<bump<terminate")
ok(idx["http_access deny drvps_internal_dst"] < idx["http_access allow drvps_connect splice_dst"]
   < idx["http_access allow drvps_connect mirror_dst"] < idx["http_access deny all"], "http_access ordering")
ok(body.rstrip("\n").splitlines()[-1] == "# egress-model-revision: " + M.model_revision(msp, P, HF2),
   "revision line == model_revision")
# a splice add leaves the CA nameConstraints hash byte-identical (no CA rotation)
ok(M.ca_hash_input(msp) == M.ca_hash_input(M.load_model({"mirror_allowlist": ["deb.debian.org"]})),
   "splice add does not change CA hash")

# ---- classify_request (port/method aware) ----
ok(M.classify_request(m0, "deb.debian.org", 443, "CONNECT") == "mirror-connect", "mirror CONNECT")
ok(M.classify_request(m0, "deb.debian.org", 80, "GET") == "mirror-get", "mirror GET:80")
ok(M.classify_request(ms, "callback.crm.example", 443, "CONNECT") == "splice-connect", "splice CONNECT")
ok(M.classify_request(m0, "callback.crm.example", 443, "CONNECT") is None, "unknown host -> None")
ok(M.classify_request(m0, "deb.debian.org", 22, "CONNECT") is None, "mirror wrong port -> None")

# ---- model_revision stable + input-sensitive ----
r1 = M.model_revision(m0, P, HF)
ok(r1 == M.model_revision(m0, P, HF), "model_revision stable")
ok(r1 != M.model_revision(ms, P, HF), "model_revision changes with model")

print("-------------------------------------------")
print("drvps-egress-model: PASS=%d FAIL=%d" % (npass[0], nfail[0]))
sys.exit(1 if nfail[0] else 0)
