#!/usr/bin/env bash
# DIFFERENTIAL render cross-check: a FROZEN shell reference renderer vs the NEW
# tools/drvps_egress_model.py CLI, over a MATRIX of identical inputs (body + CA nameConstraints).
# HISTORY: the PURE Stage-0 no-op (pre-M reference, no `-n`/`--client-requested`)
# was proven byte-identical + BACKED UP (~/BACKUPS/*egress-stage0-complete*). Stage M (mirror
# `-n`/`--client-requested`) + Stage V (strict canon) were then folded in one pass per the operator's
# "no stage stops" directive, so the FROZEN reference below is the POST-M mirror policy -- this now
# proves the CLI == the post-M reference (NOT the original pre-M no-op). Offline.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLI="$REPO/tools/drvps_egress_model.py"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
fail=0; n=0

# FROZEN verbatim copy of the OLD inline body (bin/dr-vps-setup step_proxy L1610-1637). Do NOT
# "improve" it -- it is the reference the new renderer must reproduce byte-for-byte.
old_render() {  # <proxy_ip> <proxy_src> <certgen> <cache_mb> <maxobj_mb> <mirrors...>
  local pip="$1" src="$2" certgen="$3" cache="$4" maxobj="$5"; shift 5
  local mirrors="$*" drvps_marker='# distro-rig-vps-managed squid.conf'
  printf '%s -- regenerated by dr-vps-setup; edit /etc/distro-rig-vps/fleet.json + --reapply-egress, NOT this file\n' "$drvps_marker"
  printf 'http_port %s:3128 ssl-bump cert=/etc/squid/drvps-ca.pem generate-host-certificates=on dynamic_cert_mem_cache_size=4MB\n' "$pip"
  printf 'sslcrtd_program %s -s /var/lib/ssl_db -M 4MB\n' "$certgen"
  printf 'acl drvps_guests src %s\n' "$src"
  printf 'acl mirror_sni ssl::server_name --client-requested %s\n' "$mirrors"
  printf 'acl mirror_dst dstdomain -n %s\n' "$mirrors"
  printf 'acl mirror_methods method GET HEAD\n'
  printf 'acl drvps_connect method CONNECT\n'
  printf 'acl drvps_https port 443\n'
  printf 'acl drvps_http port 80 443\n'
  printf 'acl step1 at_step SslBump1\n'
  # internal-destination deny -- ALWAYS rendered (F3: guards the mirror path too). FROZEN copy of the empty-
  # host-facts RESERVED_DENY_CIDRS set; a change to that tuple intentionally breaks this differential.
  printf 'acl drvps_internal_dst dst 0.0.0.0/8 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 169.254.0.0/16 100.64.0.0/10 192.0.0.0/24 198.18.0.0/15 240.0.0.0/4 ::/128 ::1/128 64:ff9b:1::/48 100::/64 fe80::/10 fc00::/7 fec0::/10 2001:db8::/32\n'
  printf 'ssl_bump peek step1\n'
  printf 'ssl_bump bump mirror_sni\n'
  printf 'ssl_bump terminate all\n'
  printf 'http_access deny !drvps_guests\n'
  printf 'http_access deny drvps_internal_dst\n'
  printf 'http_access allow drvps_connect mirror_dst drvps_https\n'
  printf 'http_access allow mirror_methods mirror_dst drvps_http\n'
  printf 'http_access deny all\n'
  printf 'coredump_dir /var/spool/squid\n'
  printf 'cache_dir ufs /var/spool/squid %s 16 256\n' "$cache"
  printf 'maximum_object_size %s MB\n' "$maxobj"
  printf 'cache_mem 256 MB\n'
  printf 'refresh_pattern -i \\.(rpm|drpm|xml|gz|xz|bz2|sqlite)$ 10080 90%% 43200\n'
}

# FROZEN copies of the shell CA path (bin/dr-vps-setup L132-185) -- the CA nameConstraints the new CLI
# must reproduce byte-for-byte (a mismatch rotates the CA -> golden rebuild).
_drvps_parent_domain() { printf '%s' "$1" | awk -F. '{ if (NF>=2) printf "%s.%s", $(NF-1), $NF; else printf "%s", $0 }'; }
_DRVPS_KNOWN_CA_PARENTS=" fedoraproject.org debian.org ubuntu.com rockylinux.org almalinux.org centos.org opensuse.org alpinelinux.org "
old_ca_parents() {  # <fleet.json>
  local fleet="$1" parents hosts h p d covered derived=""
  hosts=$(jq -r '.mirror_allowlist[]?' "$fleet" 2>/dev/null | sed '/^$/d')
  parents=$(jq -r '.mirror_ca_parents[]? // empty' "$fleet" 2>/dev/null)
  if [ -n "$parents" ]; then parents=$(printf '%s\n' "$parents" | sort -u | sed '/^$/d' | tr '\n' ' ')
  else for h in $hosts; do d=$(_drvps_parent_domain "$h")
      case "$_DRVPS_KNOWN_CA_PARENTS" in *" $d "*) derived="${derived:+$derived }$d";; *) return 2;; esac; done
    parents=$(printf '%s\n' $derived | sort -u | sed '/^$/d' | tr '\n' ' '); fi
  printf '%s' "$parents"
}
old_ca_nc() { local nc="excluded;IP:0.0.0.0/0.0.0.0,excluded;IP:0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0" d
  for d in $1; do nc="${nc:+$nc,}permitted;DNS:$d"; done; printf '%s' "$nc"; }

# a matrix row: JSON mirror-array | proxy_ip | proxy_src | certgen | cache | maxobj | space-mirrors
run_case() {  # <label> <mirror_json> <pip> <src> <certgen> <cache> <maxobj> <mirrors_space>
  local label="$1" mjson="$2" pip="$3" src="$4" certgen="$5" cache="$6" maxobj="$7" mspace="$8"
  n=$((n+1))
  printf '{"mirror_allowlist":%s}\n' "$mjson" > "$WORK/fleet.json"
  printf '{"proxy_ip":"%s","proxy_src":"%s","cache_mb":%s,"maxobj_mb":%s,"certgen_path":"%s"}\n' \
    "$pip" "$src" "$cache" "$maxobj" "$certgen" > "$WORK/params.json"
  printf '{}\n' > "$WORK/hf.json"
  old_render "$pip" "$src" "$certgen" "$cache" "$maxobj" $mspace > "$WORK/old.conf"
  python3 "$CLI" render --fleet "$WORK/fleet.json" --params "$WORK/params.json" --host-facts "$WORK/hf.json" > "$WORK/new.conf"
  if diff -u "$WORK/old.conf" "$WORK/new.conf" > "$WORK/diff.txt"; then
    echo "PASS  body  $label"
  else
    echo "FAIL  body  $label"; sed 's/^/    /' "$WORK/diff.txt"; fail=1
  fi
  # CA nameConstraints must also match byte-for-byte (else the CA rotates)
  old_ca_nc "$(old_ca_parents "$WORK/fleet.json")" > "$WORK/old.nc"
  python3 "$CLI" ca-nameconstraints --fleet "$WORK/fleet.json" | tr -d '\n' > "$WORK/new.nc"
  if diff -u "$WORK/old.nc" "$WORK/new.nc" > "$WORK/ncdiff.txt"; then
    echo "PASS  ca-nc $label"
  else
    echo "FAIL  ca-nc $label"; sed 's/^/    /' "$WORK/ncdiff.txt"; fail=1
  fi
}

LIVE='["mirrors.fedoraproject.org","download.fedoraproject.org","dl.fedoraproject.org","deb.debian.org","cloud.debian.org","security.debian.org","archive.ubuntu.com","security.ubuntu.com","dl.rockylinux.org","repo.almalinux.org","mirror.stream.centos.org","download.opensuse.org","dl-cdn.alpinelinux.org"]'
LIVE_S='mirrors.fedoraproject.org download.fedoraproject.org dl.fedoraproject.org deb.debian.org cloud.debian.org security.debian.org archive.ubuntu.com security.ubuntu.com dl.rockylinux.org repo.almalinux.org mirror.stream.centos.org download.opensuse.org dl-cdn.alpinelinux.org'

run_case "live-set default knobs" "$LIVE" 10.123.0.1 10.123.0.0/24 /usr/lib64/squid/security_file_certgen 8192 2048 "$LIVE_S"
run_case "single mirror"           '["deb.debian.org"]' 10.123.0.1 10.123.0.0/24 /usr/lib/squid/security_file_certgen 8192 2048 "deb.debian.org"
run_case "alt ip/src/cache/maxobj" '["deb.debian.org","archive.ubuntu.com"]' 10.200.0.1 10.200.0.0/24 /usr/libexec/squid/security_file_certgen 4096 1024 "deb.debian.org archive.ubuntu.com"
run_case "two fedora"              '["dl.fedoraproject.org","download.fedoraproject.org"]' 10.123.0.1 10.123.0.0/24 /usr/lib64/squid/security_file_certgen 16384 512 "dl.fedoraproject.org download.fedoraproject.org"

echo "-------------------------------------------"
echo "egress render no-op differential: $n cases, $([ $fail = 0 ] && echo ALL-IDENTICAL || echo MISMATCH)"
exit $fail
