#!/usr/bin/env python3
"""drvps egress MODEL + PURE renderer/canonicalizer (CONCEPT-EGRESS-SPLICE C-§6/§9a.D;
PLAN Task 0.1). NO IO / env / CA / service side effects -- it takes an already-parsed fleet dict
plus explicit typed RenderParams + HostFacts and returns strings. Orchestration (dr-vps-setup, the
approve script) does discovery and passes facts IN. ASCII only.

STAGE 0 scope: `canon_fqdn`, the LEGACY mirror loader, the byte-identical mirror-only `render_squid`,
the CA-parent/nameConstraints/hash functions, `classify_request`, `model_revision`. The splice render
branch + strict mirror canonicalization land in later staged tasks; splice parsing is validated here
(forward-looking) but Stage-0 rendering ignores it, so an empty splice list is byte-identical.
"""
from __future__ import annotations
import dataclasses
import hashlib
import json
import re
import sys

# ---- the frozen managed-file marker (must match dr-vps-setup step_proxy verbatim) ----------------
MARKER = ("# distro-rig-vps-managed squid.conf -- regenerated by dr-vps-setup; "
          "edit /etc/distro-rig-vps/fleet.json + --reapply-egress, NOT this file")

# The ONLY registrable domains dr-vps-setup will AUTO-DERIVE a CA parent for (else fail closed).
KNOWN_CA_PARENTS = frozenset(
    "fedoraproject.org debian.org ubuntu.com rockylinux.org almalinux.org "
    "centos.org opensuse.org alpinelinux.org".split())

# nameConstraints IP-exclusion prefix, byte-for-byte as _drvps_ca_nc emits it.
_NC_IP_EXCLUDE = "excluded;IP:0.0.0.0/0.0.0.0,excluded;IP:0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0"

# validation ReasonCode + durable DecisionReason (PLAN r2/r3 typed enums)
REASON_CODES = frozenset((
    "bad-label", "too-long", "leading-dash", "ip-literal", "url", "port", "wildcard",
    "non-ascii", "single-label", "overlap", "dup", "bad-type", "bad-port",
    "malformed-storage", "oversize", "wrong-owner", "unknown-field"))
DECISION_REASONS = frozenset(("applied", "already-active", "already-absent",
                              "operator-declined", "expired")) | REASON_CODES

_LABEL = re.compile(r"\A[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\Z")   # 1-63, start/end alnum
_IPV4 = re.compile(r"\A[0-9]{1,3}(\.[0-9]{1,3}){3}\Z")

# internal-destination deny set (C-§6.3): the special-purpose / non-global ranges most likely to FRONT an
# internal host, so a rebinding/compromised allowlisted name (mirror OR splice) can't be tunnelled inward.
# Covers: UNSPECIFIED (0.0.0.0/8, ::/128 -- connecting to which reaches host loopback on Linux), loopback,
# RFC1918, CGNAT, link-local, IETF-protocol (192.0.0.0/24), benchmarking (198.18.0.0/15), reserved/future
# (240.0.0.0/4), and the genuinely-IPv6 special ranges: local-use NAT64 (64:ff9b:1::/48, RFC 8215), discard
# (100::/64), link/site-local (fe80::/10, fec0::/10), ULA (fc00::/7), documentation (2001:db8::/32).
# DELIBERATELY EXCLUDED -- prefixes that ENCODE an IPv4 address, because denying the whole prefix denies the
# public IPv4 space it maps and breaks legitimate egress:
#   * ::ffff:0:0/96 (IPv4-mapped): squid stores EVERY IPv4 destination internally as an IPv4-mapped address, so
#     `dst ::ffff:0:0/96` matches ALL IPv4 and is a total outage (the container behavioral gate caught this).
#     It is also redundant -- squid normalizes v4-mapped back to v4, so 127.0.0.0/8 et al. already cover it.
#   * 64:ff9b::/96 (well-known NAT64, IANA GLOBALLY-REACHABLE): on a NAT64 host this legitimately represents
#     public IPv4 callbacks; a blanket deny blocks them. Only the local-use 64:ff9b:1::/48 is kept.
# NOT PURSUED (documented rejection, not an oversight): exhaustive IANA-registry completeness (e.g. the v4
# documentation blocks 192.0.2.0/24 / 198.51.100.0/24 / 203.0.113.0/24). They are a weak SSRF vector (reserved,
# not used to front real services) AND 192.0.2.50 is the conventional public stand-in used by the behavioral
# tunnel test; chasing full-registry parity is unbounded and risks re-introducing an over-broad prefix.
# The drvps-specific ranges (subnets, host IPs, block_cidrs) come from HostFacts and are appended.
RESERVED_DENY_CIDRS = (
    "0.0.0.0/8", "127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16",
    "169.254.0.0/16", "100.64.0.0/10", "192.0.0.0/24", "198.18.0.0/15", "240.0.0.0/4",
    "::/128", "::1/128", "64:ff9b:1::/48", "100::/64",
    "fe80::/10", "fc00::/7", "fec0::/10", "2001:db8::/32")


class EgressError(ValueError):
    """Raised on an invalid egress model; .reason is a ReasonCode."""
    def __init__(self, reason: str, detail: str = ""):
        super().__init__("%s%s" % (reason, (": " + detail) if detail else ""))
        self.reason = reason


def canon_fqdn(raw):
    """ANY value -> (canonical_host, None) or (None, ReasonCode). Total; never raises. C-§6.1."""
    if not isinstance(raw, str):
        return (None, "bad-type")
    if not raw.isascii():                 # IDN must be pre-converted to xn--
        return (None, "non-ascii")
    if "/" in raw:
        return (None, "url")
    if ":" in raw:                        # embedded port or IPv6 literal
        return (None, "port")
    if "*" in raw:
        return (None, "wildcard")
    s = raw.lower()
    if s.startswith("-"):                 # a leading '-' could be read by Squid as an ACL option
        return (None, "leading-dash")
    if s.startswith(".") or s.endswith(".") or ".." in s:
        return (None, "bad-label")
    if len(s) > 253:
        return (None, "too-long")
    if _IPV4.match(s):
        return (None, "ip-literal")
    labels = s.split(".")
    if len(labels) < 2:
        return (None, "single-label")
    for lab in labels:
        if len(lab) > 63:
            return (None, "too-long")
        if not _LABEL.match(lab):
            return (None, "bad-label")
    return (s, None)


def parent_domain(fqdn: str) -> str:
    """last two dot-labels (matches dr-vps-setup _drvps_parent_domain)."""
    parts = fqdn.split(".")
    return ".".join(parts[-2:]) if len(parts) >= 2 else fqdn


@dataclasses.dataclass(frozen=True)
class RenderParams:
    proxy_ip: str
    proxy_src: str
    cache_mb: int
    maxobj_mb: int
    certgen_path: str


@dataclasses.dataclass(frozen=True)
class HostFacts:
    # internal-deny inputs (Stage 1 `internal_deny_cidrs`); unused by the Stage-0 mirror render.
    drvps_subnets: tuple = ()
    host_ips: tuple = ()
    fleet_public_ips: tuple = ()
    block_cidrs: tuple = ()


@dataclasses.dataclass(frozen=True)
class EgressModel:
    mirrors: tuple                  # LEGACY tokens, order preserved
    mirror_ca_parents_raw: tuple    # explicit fleet.mirror_ca_parents (canonical) or ()
    splices: tuple                  # ((host, port), ...) canonicalized, disjoint from mirrors


def _as_list(v, what):
    if v is None:
        return []
    if not isinstance(v, list):
        raise EgressError("bad-type", what)
    return v


def load_model(fleet: dict) -> EgressModel:
    """Parse a fleet dict into an EgressModel. Mirrors keep the LEGACY charset loader (Stage 0 is a
    no-op; strict mirror canonicalization is the later Stage V). Splices go through canon_fqdn now."""
    if not isinstance(fleet, dict):
        raise EgressError("bad-type", "fleet")
    mirrors = []
    seen_m = set()
    for m in _as_list(fleet.get("mirror_allowlist"), "mirror_allowlist"):
        host, reason = canon_fqdn(m)                     # Stage V: strict canonicalization
        if host is None:
            raise EgressError(reason, "mirror %r" % (m,))
        if host in seen_m:                               # fail closed on a duplicate mirror
            raise EgressError("dup", "mirror %s" % host)
        seen_m.add(host)
        mirrors.append(host)
    parents_raw = []
    for p in _as_list(fleet.get("mirror_ca_parents"), "mirror_ca_parents"):
        host, reason = canon_fqdn(p)
        if host is None:
            raise EgressError(reason, "ca_parent %r" % (p,))
        parents_raw.append(host)
    mirror_lc = {m.lower() for m in mirrors}
    seen = set()
    splices = []
    for e in _as_list(fleet.get("splice_allowlist"), "splice_allowlist"):
        if not isinstance(e, dict):
            raise EgressError("bad-type", "splice entry")
        extra = set(e) - {"host", "port"}
        if extra:
            raise EgressError("unknown-field", ",".join(sorted(extra)))
        host, reason = canon_fqdn(e.get("host"))
        if host is None:
            raise EgressError(reason, "splice host %r" % (e.get("host"),))
        port = e.get("port", 443)
        # v1 is 443-only -- the renderer emits a single drvps_https(443) allow, so accepting any other
        # port would store an entry that can never work. Reject it fail-closed;
        # multi-port is a future stage (the schema keeps the field).
        if not isinstance(port, int) or isinstance(port, bool) or port != 443:
            raise EgressError("bad-port", "v1 supports only port 443 (got %r)" % (port,))
        if host in mirror_lc:
            raise EgressError("overlap", host)      # a host cannot be both bumped and spliced
        if host in seen:
            raise EgressError("dup", host)
        seen.add(host)
        splices.append((host, port))
    return EgressModel(tuple(mirrors), tuple(parents_raw), tuple(splices))


def ca_parents(model: EgressModel):
    """Canonical permitted CA parent domains (matches _drvps_ca_parents). Raises EgressError
    (fail closed) on an unknown family with no explicit mirror_ca_parents, or an uncovered mirror."""
    if model.mirror_ca_parents_raw:
        parents = sorted(set(model.mirror_ca_parents_raw))
    else:
        derived = set()
        for h in model.mirrors:
            d = parent_domain(h)
            if d not in KNOWN_CA_PARENTS:
                raise EgressError("bad-label", "no safe auto cache-CA parent for mirror '%s'" % h)
            derived.add(d)
        parents = sorted(derived)
    if not parents:
        raise EgressError("bad-label", "no cache-CA parents")
    for p in parents:
        if "." not in p:
            raise EgressError("bad-label", "cache-CA parent '%s' is not a domain" % p)
    for h in model.mirrors:                        # every mirror must be covered by some parent
        if not any(h == p or h.endswith("." + p) for p in parents):
            raise EgressError("bad-label", "mirror '%s' not covered by any cache-CA parent" % h)
    return parents


def render_ca_name_constraints(model: EgressModel) -> str:
    """The OpenSSL nameConstraints value (matches _drvps_ca_nc). Splice hosts are NOT included."""
    nc = _NC_IP_EXCLUDE
    for d in ca_parents(model):
        nc += ",permitted;DNS:" + d
    return nc


def ca_hash_input(model: EgressModel) -> str:
    """The exact string dr-vps-setup hashes for CA-regen drift detection (the nameConstraints)."""
    return render_ca_name_constraints(model)


def internal_deny_cidrs(model: EgressModel, host_facts: HostFacts):
    """The `acl drvps_internal_dst dst ...` set (C-§6.3/9a.K): reserved/non-global ranges PLUS the
    drvps-specific ranges from HostFacts (subnets, host IPs, fleet public IPs, operator block_cidrs).
    Deterministic, deduplicated, reserved-first order. So a rebinding/compromised public name can never
    resolve to loopback/LAN/host and slip through the spliced tunnel."""
    out = list(RESERVED_DENY_CIDRS)
    for c in (tuple(host_facts.drvps_subnets) + tuple(host_facts.host_ips)
              + tuple(host_facts.fleet_public_ips) + tuple(host_facts.block_cidrs)):
        if c not in out:
            out.append(c)
    return out


def render_squid(model: EgressModel, params: RenderParams, host_facts: HostFacts) -> str:
    """The FULL managed squid.conf body incl. the marker + a trailing model-revision comment.
    Mirror ACLs are pinned to the client SNI + reverse-DNS-off (`-n`) [Stage M bugfix]. The
    internal-destination deny (`drvps_internal_dst`) is ALWAYS rendered -- it guards the always-on
    mirror path AND any splice. When splice_allowlist is non-empty, the splice branch additionally
    adds the conjunctive dst+sni ssl_bump rules and `on_unsupported_protocol respond all` [C-§4]."""
    mirrors = " ".join(model.mirrors)
    has_splice = bool(model.splices)
    L = [
        MARKER,
        ("http_port %s:3128 ssl-bump cert=/etc/squid/drvps-ca.pem "
         "generate-host-certificates=on dynamic_cert_mem_cache_size=4MB" % params.proxy_ip),
        "sslcrtd_program %s -s /var/lib/ssl_db -M 4MB" % params.certgen_path,
        "acl drvps_guests src %s" % params.proxy_src,
        "acl mirror_sni ssl::server_name --client-requested %s" % mirrors,
        "acl mirror_dst dstdomain -n %s" % mirrors,
    ]
    if has_splice:
        sh = " ".join(h for (h, _p) in model.splices)
        L += ["acl splice_sni ssl::server_name --client-requested %s" % sh,
              "acl splice_dst dstdomain -n %s" % sh]
    L += [
        "acl mirror_methods method GET HEAD",
        "acl drvps_connect method CONNECT",
        "acl drvps_https port 443",
        "acl drvps_http port 80 443",
        "acl step1 at_step SslBump1",
    ]
    # internal-destination deny (SSRF / DNS-rebinding): ALWAYS defined + denied, NOT only when a splice exists.
    # The mirror allowlist is always active, and an allowlisted mirror name that is compromised or resolves
    # through poisoned DNS to an internal address is the SAME SSRF as a rebinding splice callback -- so the
    # `dst` deny must guard the mirror path too, ordered before EVERY http_access allow. (Previously this was
    # gated on has_splice, leaving the default mirror-only config unprotected -- external review finding.)
    L += ["acl drvps_internal_dst dst %s" % " ".join(internal_deny_cidrs(model, host_facts))]
    if has_splice:
        L += ["acl step2 at_step SslBump2"]
    L += ["ssl_bump peek step1"]
    if has_splice:                                  # bind BOTH dst AND sni per action
        L += ["ssl_bump splice step2 splice_dst splice_sni",
              "ssl_bump bump step2 mirror_dst mirror_sni"]
    else:
        L += ["ssl_bump bump mirror_sni"]
    L += ["ssl_bump terminate all",
          "http_access deny !drvps_guests",
          "http_access deny drvps_internal_dst"]    # ALWAYS before any allow (mirror + splice both guarded)
    if has_splice:
        L += ["http_access allow drvps_connect splice_dst drvps_https"]
    L += [
        "http_access allow drvps_connect mirror_dst drvps_https",
        "http_access allow mirror_methods mirror_dst drvps_http",
        "http_access deny all",
    ]
    if has_splice:
        L += ["on_unsupported_protocol respond all"]
    L += [
        "coredump_dir /var/spool/squid",
        "cache_dir ufs /var/spool/squid %s 16 256" % params.cache_mb,
        "maximum_object_size %s MB" % params.maxobj_mb,
        "cache_mem 256 MB",
        r"refresh_pattern -i \.(rpm|drpm|xml|gz|xz|bz2|sqlite)$ 10080 90% 43200",
    ]
    if has_splice:                                  # self-describing revision for the doctor drift check
        L += ["# egress-model-revision: %s" % model_revision(model, params, host_facts)]
    return "\n".join(L) + "\n"


def classify_request(model: EgressModel, host, port, method):
    """port + method aware (C-§9a). -> mirror-connect | mirror-get | splice-connect | None."""
    h = host.lower() if isinstance(host, str) else host
    is_mirror = h in {m.lower() for m in model.mirrors}
    is_splice = h in {s[0] for s in model.splices}
    if is_splice and method == "CONNECT" and port == 443:
        return "splice-connect"
    if is_mirror and method == "CONNECT" and port == 443:
        return "mirror-connect"
    if is_mirror and method in ("GET", "HEAD") and port in (80, 443):
        return "mirror-get"
    return None


def model_revision(model: EgressModel, params: RenderParams, host_facts: HostFacts) -> str:
    """Stable hash of the canonical render inputs (C-§9a.L)."""
    blob = json.dumps({
        "mirrors": list(model.mirrors),
        "ca_parents": ca_parents(model),
        "splices": [[h, p] for (h, p) in model.splices],
        "params": dataclasses.asdict(params),
        "host_facts": dataclasses.asdict(host_facts),
    }, sort_keys=True, separators=(",", ":")).encode("ascii")
    return hashlib.sha256(blob).hexdigest()


# ---- orchestration CLI (PLAN Task 0.2): the ONE seam shell/approve call; pure funcs stay pure ------
def _read_json(path):
    with open(path, "r") as fh:
        return json.load(fh)


def main(argv):
    import argparse
    ap = argparse.ArgumentParser(prog="drvps_egress_model", description="drvps egress renderer")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("render", "revision"):
        p = sub.add_parser(name)
        p.add_argument("--fleet", required=True); p.add_argument("--params", required=True)
        p.add_argument("--host-facts", required=True)
    p = sub.add_parser("ca-nameconstraints"); p.add_argument("--fleet", required=True)
    p = sub.add_parser("classify")
    p.add_argument("--fleet", required=True); p.add_argument("--host", required=True)
    p.add_argument("--port", required=True, type=int); p.add_argument("--method", required=True)
    args = ap.parse_args(argv)
    try:
        model = load_model(_read_json(args.fleet))
        if args.cmd == "ca-nameconstraints":
            sys.stdout.write(render_ca_name_constraints(model) + "\n"); return 0
        if args.cmd == "classify":
            r = classify_request(model, args.host, args.port, args.method)
            sys.stdout.write((r or "none") + "\n"); return 0
        params = RenderParams(**_read_json(args.params))
        hf = HostFacts(**{k: tuple(v) for k, v in _read_json(args.host_facts).items()})
        if args.cmd == "render":
            sys.stdout.write(render_squid(model, params, hf)); return 0
        if args.cmd == "revision":
            sys.stdout.write(model_revision(model, params, hf) + "\n"); return 0
    except EgressError as e:
        sys.stderr.write("egress-error: %s\n" % e.reason); return 3
    except (OSError, ValueError, TypeError) as e:
        sys.stderr.write("egress-input: %s\n" % e); return 2
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
